version: '3.9'

services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    command: dgraph zero --my=zero:5080

  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=172.0.0.0/8

  ratel:
    image: dgraph/ratel:latest
    ports:
      - 8000:8000

volumes:
  dgraph: {}
